### PR TITLE
fix: correctly serialize a multsig call, then parse WrapperKeepOpaque, and WrapperOpaque

### LINKED ISSUE #835: v11.3.8 not parse call parameters
v11.3.8 return block info, not parse call parameters
image
This is the return information of the previous version
image
Mind if you can parse all call parameters, such as proposal preimage

### PR DESCRIPTION
**Pull request by TarikGul**
closes: [#835](https://github.com/paritytech/substrate-api-sidecar/issues/835)

This PR resolves serializing a MultiSig call and correctly parsing the args with the added `WrapperKeepOpaque`, and `WrapperOpaque` types. The code is a little repetitive to keep it readable, and understandable, also `parseGenericCalls` is heavily leveraging recursion so best to not mess with the logic much. 

I added an e2e test for the block mentioned in the issue to ensure we are tracking a `WrapperKeepOpaque` call. 

This is via polkadot-js/api v7.6.1

### CODE REVIEW

File: src/services/blocks/BlocksService.ts [hunk 1]
```diff
@@ -709,6 +709,30 @@ export class BlocksService extends AbstractService {
 					} catch {
 						newArgs[paramName] = argument;
 					}
+				} else if (
+					paramName === 'call' &&
+					argument?.toRawType() === 'WrapperKeepOpaque<Call>'
+				) {
+					// multiSig.asMulti.args.call is also an WrapperKeepOpaque<Call> (Vec<u8>) that we
+					// serialize to a polkadot-js Call and parse so it is not a hex blob.
```
Comment (jarcodallo) [inline src/services/blocks/BlocksService.ts:717]: Why not remove this comments?

File: src/services/blocks/BlocksService.ts [hunk 2]
```diff
@@ -709,6 +709,30 @@ export class BlocksService extends AbstractService {
...
+						newArgs[paramName] = this.parseGenericCall(call, registry);
+					} catch {
+						newArgs[paramName] = argument;
+					}
+				} else if (
+					paramName === 'call' &&
+					argument?.toRawType() === 'WrapperOpaque<Call>'
+				) {
+					// multiSig.asMulti.args.call is also an WrapperKeepOpaque<Call> (Vec<u8>) that we
+					// serialize to a polkadot-js Call and parse so it is not a hex blob.
```
Comment (jarcodallo) [inline src/services/blocks/BlocksService.ts:729]: same

File: src/services/blocks/BlocksService.ts [hunk 3]
```diff
@@ -701,14 +701,35 @@ export class BlocksService extends AbstractService {
...
+				} else if (
+					paramName === 'call' &&
+					argument?.toRawType() === 'WrapperOpaque<Call>'
+				) {
+					try {
+						const call = registry.createType('Call', argument.toHex());
+						newArgs[paramName] = this.parseGenericCall(call, registry);
+					} catch {
+						newArgs[paramName] = argument;
+					}
```
Comment (jsdw) [inline src/services/blocks/BlocksService.ts:732]: Ah ok, so basically these bits are the same as something like the following then I guess?:

```
} else if (argument && paramName === 'call' && ['Bytes', 'WrapperKeepOpaque<Call>', 'WrapperOpaque<Call>'].includes(argument.toRawType())) {
	// multiSig.asMulti.args.call is either an OpaqueCall (Vec<u8>),
	// WrapperKeepOpaque<Call>, or WrapperOpaque<Call> that we
	// serialize to a polkadot-js Call and parse so it is not a hex blob.
	try {
		const call = registry.createType('Call', argument.toHex());
		newArgs[paramName] = this.parseGenericCall(call, registry);
	} catch {
		newArgs[paramName] = argument;
	}
} else {
	newArgs[paramName] = argument;
}
```

**Review by jsdw — APPROVED** [review]
LGTM, not a big fan of the repetition since it is identical even at a type level but up to you :)

File: src/services/blocks/BlocksService.ts (hunk 3 above)
Comment (TarikGul) [reply src/services/blocks/BlocksService.ts:732]: Yea that is way cleaner, ill change it to reflect that. Thanks!

Comment (TarikGul) [reply src/services/blocks/BlocksService.ts]: fixed

**Comment by TarikGul** [comment]
@jsdw I made the changes to stop the repetition, i totally agree that the solution you provided was way better.

File: src/services/blocks/BlocksService.ts [hunk 4]
```diff
@@ -700,8 +700,15 @@ export class BlocksService extends AbstractService {
...
-					// multiSig.asMulti.args.call is an OpaqueCall (Vec<u8>) that we
+				} else if (
+					argument &&
+					paramName === 'call' &&
+					['Bytes', 'WrapperKeepOpaque<Call>', 'WrapperOpaque<Call>'].includes(
+						argument?.toRawType()
+					)
+				) {
+					// multiSig.asMulti.args.call is either an OpaqueCall (Vec<u8>),
+					// WrapperKeepOpaque<Call>, or WrapperOpaque<Call> that we
```
Comment (dvdplm) [inline src/services/blocks/BlocksService.ts:711]: It's a bit hard to map the code in the `try…catch` block to each of the three cases. What do you think about something like this:

```ts
			} else if (
				argument &&
				paramName === 'call'
			) {
				switch (argument?.toRawType()) {
					case 'Bytes':
					case 'WrapperKeepOpaque<Call>':	
						newArgs[paramName] = argument;
					case 'WrapperOpaque<Call>':
						const call = registry.createType('Call', argument.toHex());
						newArgs[paramName] = this.parseGenericCall(call, registry);
	
					default:
						// log or otherwise report error?;
				}
```

(Not sure I got the cases right, which is illustrating the point I guess)

Comment (niklasad1) [reply src/services/blocks/BlocksService.ts:711]: I like that if that works :)

**Review by niklasad1 — APPROVED** [review]

File: src/services/blocks/BlocksService.ts (hunk 4 above)
Comment (TarikGul) [reply src/services/blocks/BlocksService.ts:711]: So actually each of the 3 cases are going to map out to the same output i.e.
```
					try {
						const call = registry.createType('Call', argument.toHex());
						newArgs[paramName] = this.parseGenericCall(call, registry);
					} catch {
						newArgs[paramName] = argument;
					}
```

therefore the above wont work. I filed an issue [here](https://github.com/paritytech/substrate-api-sidecar/issues/845) regarding the `try catch` in order to potentially optimize it. For this PR i think it is out of scope as we are just extending the conditional to include `WrapperKeepOpaque<Call>`, and `WrapperOpaque`.

**Comment by TarikGul** [comment]
Merging. @dvdplm I think your comment has some merit above, and should be given some extra investigation and potential optimization. That being said, for the scope of this PR, lets just patch the bug (since the solution itself is pretty simple and doesnt change any of the core logic when parsing the generic calls). But I will follow this PR up with the issue I filed and see what we can do :)
