### PR TITLE
fix: add TransactionPayment::TransactionPaidFee support

### LINKED ISSUE #756: Fetch tx fee from onchain events
It will be useful if there is a mode to query tx fee info from onchain events data instead of calculating it.

But need to consider about https://github.com/paritytech/polkadot/issues/4230

### PR DESCRIPTION
**Pull request by TarikGul**
closes: https://github.com/paritytech/substrate-api-sidecar/issues/756 https://github.com/paritytech/substrate-api-sidecar/issues/971

This is a continuation of https://github.com/paritytech/substrate-api-sidecar/pull/1017. For all future blocks that have the event `TransactionPayment::TransactionPaidFee` we will retrieve the fee directly from the event. 

Adds a `fromEvent` dispatchFeeType.

### CODE REVIEW

File: src/services/blocks/BlocksService.ts [hunk 1]
```diff
@@ -264,40 +265,50 @@ export class BlocksService extends AbstractService {
...
-				finalPartialFee = await this.fetchQueryFeeDetails(
-					block.extrinsics[idx].toHex(),
-					previousBlockHash,
-					weightInfo.weight,
-					weight
-				);
-
+			if (transactionPaidFeeEvent) {
+				finalPartialFee = transactionPaidFeeEvent.data[1].toString();
 				dispatchFeeType = 'postDispatch';
```
Comment (jsdw) [inline src/services/blocks/BlocksService.ts:277]: Wondering whether adding a new `dispatchFeeType` for this (eg `fromEvent`) makes sense?

Why? because the queryFee logic we use is hardcoded to follow the polkadot fee payment approach and may not work in chains that do something different, so adding a new dispatchFeeType allows chains to know whether they can rely on the value or not if they differ.

Comment (TarikGul) [reply src/services/blocks/BlocksService.ts:277]: Ahh that makes complete sense. I think this is valid, and I agree that a `fromEvent` `dispatchFeeType` is a nice addition.

Comment (TarikGul) [reply src/services/blocks/BlocksService.ts]: Added `fromEvent` dispatchFeeType

**Review by niklasad1 — APPROVED** [review]
LGTM

**Review by lexnv — APPROVED** [review]
