### PR TITLE
fix: Use http BadRequest (400) when balance-info not found

### LINKED ISSUE #346: Use `http-errors` in `accounts/{accountId}/balance-info`
To align with the rest of the service, this should use `http-errors`: 

https://github.com/paritytech/substrate-api-sidecar/blob/eeea29b74ef50eb45356e4a7e1ea04344097cc00/src/services/accounts/AccountsBalanceInfoService.ts#L49

Should look similar too:

https://github.com/paritytech/substrate-api-sidecar/blob/eeea29b74ef50eb45356e4a7e1ea04344097cc00/src/services/accounts/AccountsStakingInfoService.ts#L31

### PR DESCRIPTION
**Pull request by emostov**
Closes #346 

Also uses `.unwrap()` on the `Compact` block number, which should be more idiomatic then using `.toNumber()`.

### CODE REVIEW

File: src/services/accounts/AccountsBalanceInfoService.ts [hunk 1]
```diff
@@ -29,7 +30,7 @@ export class AccountsBalanceInfoService extends AbstractService {
 
 		const at = {
 			hash,
-			height: header.number.toNumber().toString(10),
+			height: header.number.unwrap().toString(10),
```
Comment (dvdplm) [inline src/services/accounts/AccountsBalanceInfoService.ts:33]: afaiu this isn't anything like the Rust `unwrap()` right? It literally removes the wrapping?

**Review by dvdplm — APPROVED** [review]

File: src/services/accounts/AccountsBalanceInfoService.ts (hunk 1 above)
Comment (niklasad1) [reply src/services/accounts/AccountsBalanceInfoService.ts:33]: haha, yeah this is confusing when `unwrap` is a nasty habit in Rust :)

**Review by niklasad1 — APPROVED** [review]
