### PR TITLE
Get Block Should Accept Hash

### LINKED ISSUE #76: Get Block Should Accept Hash
A lot of systems, including Sidecar's console log, identify blocks by hash rather than number. the `block/:number` endpoint should be able to accept either an int or a hash and return the block accordingly. 

Sample error from Sidecar's console:
```
Internal Error: Error: Missing extrinsic 2 in block 0x9e49962fbbfca0d6921e422e4fc4e3e5efbf4cfe3318847697c035891e9c0a12
```

### PR DESCRIPTION
**Pull request by danforbes**
Closes #76

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -120,8 +122,13 @@ async function main() {
 	});
 
 	get('/block/:number', async (params) => {
-		const number = parseNumber(params.number);
-		const hash = await api.rpc.chain.getBlockHash(number);
+		let hash: BlockHash;
+		if (isHex(params.number)) {
```
Comment (joepetrowski) [inline src/main.ts:126]: So, I know with txwrapper, you can construct an unsigned transaction with the block number in hex, like '0x1234'. Makes me wonder two things:
1. Some users might just have hex everything, in which case this should also check that the hex is 32 bytes.
2. Maybe Polkadot JS already has a nice function for this logic?

Comment (danforbes) [reply src/main.ts:126]: Yeah, totally good point :+1:

Comment (amaurymartiny) [reply src/main.ts:127]: Yeah correct. I'm not aware of any helper function in polkadot-js, but 32-byte check should be fine.

There's an edge case where the hex-encoded number is 32-bytes, but this should happen in the very distant future, so no worries. Another approach, without disambiguation, would be to have another endpoint `/blockByHash/:hash`

**Comment by danforbes** [comment]
Converting this to draft so I can rebase on top of the ESLint changes :rocket:

**Comment by danforbes** [comment]
Okay rebased and linted :+1:

File: src/main.ts [hunk 2]
```diff
@@ -454,4 +445,33 @@ async function main() {
...
+	api: ApiPromise,
+	blockId: string
+): Promise<BlockHash> {
+	try {
+		const isHexStr = isHex(blockId);
+		if (isHexStr && blockId.length === 66) {
+			return api.createType('BlockHash', blockId);
+		} else if (isHexStr) {
+			throw {
+				error: `Cannot get block hash for ${blockId}. Hex string block IDs must be 66-characters (32-bytes) in length.`,
```
Comment (joepetrowski) [inline src/main.ts:458]: I think it'd be good to convert this to a number if some people's systems use hex. There's no way block number collides with a hash that's 32 bytes.

Comment (emostov) [reply src/main.ts]: Not sure I totally understand, but would [the conversion](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/utils.ts#L8) be surfacing an additional point of failure/ misdirection that could obscure the original error? i.e if someone accidentally sends the string "Hello", but we convert it to a number before interpolating into the error message, it could throw off debugging.

Comment (danforbes) [reply src/main.ts]: Yeah, I think I'm with Zeke on this one but I'm still not completely sure this is what Joe was suggesting so I'll just hold off.
