### PR TITLE
fix: Use correct registry when creating calls; Remove usage of derive.chain.getBlock

### LINKED ISSUE #384: Westend: Error: createType(Call):: findMetaCall: Unable to find Call with index 0x0900/[9,0]
Description

code: lastest commit
nodejs: v14 LTS
network: westend testnet
polkadot: v1.8.27

Steps to Reproduce

request for `/blocks/3809155` and get `createType(Call):: findMetaCall: Unable to find Call with index 0x0900/[9,0]`

```
2021-01-13 14:19:32 error: REGISTRY: Error: findMetaCall: Unable to find Call with index 0x0900/[9,0]
    at assert (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/util/assert.js:34:11)
    at assertReturn (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/util/assert.js:44:3)
    at TypeRegistry.findMetaCall (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/registry.js:274:35)
    at decodeCallViaObject (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/generic/Call.js:57:34)
    at decodeCall (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/generic/Call.js:100:12)
    at new GenericCall (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/generic/Call.js:129:21)
    at new Type (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/registry.js:311:16)
    at initType (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.js:69:12)
    at createType (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.js:84:10)
2021-01-13 14:19:32 error: createType(Call):: findMetaCall: Unable to find Call with index 0x0900/[9,0] 
 Error: createType(Call):: findMetaCall: Unable to find Call with index 0x0900/[9,0]
    at createTypeUnsafe (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.js:72:11)
    at createType (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/registry.js:268:39)
    at /project/github.com/polkadot-js/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:145:41
        -> /project/github.com/polkadot-js/substrate-api-sidecar/src/services/blocks/BlocksService.ts:226:32
    at Array.map (<anonymous>)
    at Array.map (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/codec/AbstractArray.js:151:27)
    at BlocksService.extractExtrinsics (/project/github.com/polkadot-js/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:142:33)
        -> /project/github.com/polkadot-js/substrate-api-sidecar/src/services/blocks/BlocksService.ts:216:27
    at BlocksService.fetchBlock (/project/github.com/polkadot-js/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:52:45)
        -> /project/github.com/polkadot-js/substrate-api-sidecar/src/services/blocks/BlocksService.ts:81:39
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async BlocksController.getBlockById (/project/github.com/polkadot-js/substrate-api-sidecar/build/src/controllers/blocks/BlocksController.js:92:49)
        -> /project/github.com/polkadot-js/substrate-api-sidecar/src/controllers/blocks/BlocksController.ts:125:4
```

Expected vs. Actual Behavior

should no error here

### PR DESCRIPTION
**Pull request by emostov**
Closes #384 

In https://github.com/paritytech/substrate-api-sidecar/pull/351, I removed the querys `api.query.session.validators` & `api.rpc.getBlock`. Additionally I removed `BlocksService. extractAuthor`. I replaced all of them with `api.derive.chain.getBlock`, which neatly gave us the `authorId` in addition to the `block`. (Opposed to having to use the validators and digest logs to extract the authorId)

However, for some reason none of the `Codec` objects returned from the derive call have a type registry dated to the call, instead they have what seems to be the most recent type registry. The effect of this is that when we try to create `Call`s that are not in the most recent metadata we get a call not found error. To solver this issue I have brought back the aforementioned code that I removed and use the type registry attached to the block

I experimented with other options like using the type registry on the block hash passed down from the controller, but that had the same issue. We also can't use the events because we do not guarantee that those will be retrieved (e.g. a non-archive node)

### CODE REVIEW

File: src/services/blocks/BlocksService.ts [hunk 1]
```diff
@@ -72,9 +68,11 @@ export class BlocksService extends AbstractService {
 			digest,
 		} = block.header;
 
-		const logs = digest.logs.map((log) => {
-			const { type, index, value } = log;
+		const authorId = sessionValidators
+			? this.extractAuthor(sessionValidators, digest)
+			: undefined;
 
+		const logs = digest.logs.map(({ type, index, value }) => {
```
Comment (kianenigma) [inline src/services/blocks/BlocksService.ts:75]: is this `.map` doing anything?

File: src/services/blocks/BlocksService.ts [hunk 2]
```diff
@@ -72,9 +68,11 @@ export class BlocksService extends AbstractService {
 			digest,
 		} = block.header;
 
-		const logs = digest.logs.map((log) => {
-			const { type, index, value } = log;
+		const authorId = sessionValidators
+			? this.extractAuthor(sessionValidators, digest)
+			: undefined;
```
Comment (dvdplm) [inline src/services/blocks/BlocksService.ts:73]: What does `extractAuthor` return? If it returns `undefined` this ternary isn't needed.
```suggestion
		const authorId = this.extractAuthor(sessionValidators, digest);
```

**Review by dvdplm — APPROVED** [review]
> However, for some reason none of the Codec objects returned from the derive call have a type registry dated to the call

Should we open an issue here (or on pd.js?) to dig into this further?

File: src/services/blocks/BlocksService.ts (hunk 1 above)
Comment (emostov) [reply src/services/blocks/BlocksService.ts:75]: Good question - I didn't dig into who wrote it / why, but it looks like it just pulls out some select fields. Not sure why it was done.

File: src/services/blocks/BlocksService.ts (hunk 2 above)
Comment (emostov) [reply src/services/blocks/BlocksService.ts:73]: We just need something so TS does not complain since it knows sessionValidators may be undefined.

File: src/services/blocks/BlocksService.ts (hunk 1 above)
Comment (TarikGul) [reply src/services/blocks/BlocksService.ts:75]: Yea so I did some further digging, its just refactoring the log data, and leaving out the fluff. 

Example: (Querying head from a local dev node)
``` typescript
// BEFORE
Vec(2) [
  Type {
    registry: TypeRegistry {},
    isOther: [Getter],
    asOther: [Getter],
    isAuthoritiesChange: [Getter],
    asAuthoritiesChange: [Getter],
    isChangesTrieRoot: [Getter],
    asChangesTrieRoot: [Getter],
    isSealV0: [Getter],
    asSealV0: [Getter],
    isConsensus: [Getter],
    asConsensus: [Getter],
    isSeal: [Getter],
    asSeal: [Getter],
    isPreRuntime: [Getter],
    asPreRuntime: [Getter]
  },
  Type {
    registry: TypeRegistry {},
    isOther: [Getter],
    asOther: [Getter],
    isAuthoritiesChange: [Getter],
    asAuthoritiesChange: [Getter],
    isChangesTrieRoot: [Getter],
    asChangesTrieRoot: [Getter],
    isSealV0: [Getter],
    asSealV0: [Getter],
    isConsensus: [Getter],
    asConsensus: [Getter],
    isSeal: [Getter],
    asSeal: [Getter],
    isPreRuntime: [Getter],
    asPreRuntime: [Getter]
  },
  registry: TypeRegistry {},
  _Type: [class Type]
]


// AFTER

[
  {
    type: 'PreRuntime',
    index: 6,
    value: Type(2) [
      [Type],
      [Bytes [Uint8Array]],
      registry: TypeRegistry {},
      _Types: [Array]
    ]
  },
  {
    type: 'Seal',
    index: 5,
    value: Type(2) [
      [Type],
      [Bytes [Uint8Array]],
      registry: TypeRegistry {},
      _Types: [Array]
    ]
  }
]
```

File: src/services/blocks/BlocksService.ts (hunk 2 above)
Comment (dvdplm) [reply src/services/blocks/BlocksService.ts:73]: eew, so you're saying we must do like `const authorId = this.extractAuthor(sessionValidators, digest) || undefined;` just to appease the compiler? :/

**Review by TarikGul — APPROVED** [review]
LGTM!

File: src/services/blocks/BlocksService.ts (hunk 2 above)
Comment (emostov) [reply src/services/blocks/BlocksService.ts:73]: Yeah, but we need to check before we call `extractAuthor`, because `extractAuthor` requires that the type of the `sessionValidators` param be `Array<AccountId>`. I agree with the compiler here because sending down `undefined` where only an array is expected could lead to issues at runtime.

Comment (dvdplm) [reply src/services/blocks/BlocksService.ts:73]: I see what you mean. But is it not an error if `sessionValidators` is `undefined` (or an empty array)? Like, shouldn't we bail before we get here if that's the case?
